config/routes.rb
Rails.application.routes.draw do
  root  "welcome#index"
  resources :students
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/student.rb
class Student < ApplicationRecord
  validates :first_name,:last_name,:email,:age,:address,presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_students,only: %i[show edit update destroy]
  def index
    @students = Student.all
  end
  
  def new
    @student = Student.new
  end

  def create
    @student = Student.create(params_students)
    if @student.save
      redirect_to students_path,notice: "Student has been Created successfully"
    else
      render :new,status: :unprocessable_entity
    end
  end

  def show 
  end

  def edit
  end

  def update
    if @student.update(params_students)
      redirect_to students_path,notice: "Student has been Updated successfully"
    else
      render :new
    end
  end

  def destroy
    @student.destroy
    redirect_to students_path,notice: "Student has been Deleted successfully"
  end

  private
  def params_students
    params.require(:student).permit(:first_name,:last_name,:email,:age,:address)
  end

  def set_students
    @student = Student.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/edit.html.erb
<h1>Edit Student's</h1>
<%= form_with model: @student do |form| %>
  <% if @student.errors.any? %>
      <% @student.errors.full_messages.each do |messages| %>
          <p><%= messages %></p>
      <%end%>
  <%end%>

  <div>
  <%= form.label :first_name %><br>
  <%= form.text_field :first_name %>
  </div>
  <br>

  <div>
  <%= form.label :last_name %><br>
  <%= form.text_field :last_name %>
  </div>
  <br>

  </div>
  <%= form.label :email %><br>
  <%= form.text_field :email %>
  </div>
  <br><br>
  
  <div>
  <%= form.label :age %><br>
  <%= form.text_area :age %>
  </div>
  <br>

  <div>
  <%= form.label :address %><br>
  <%= form.text_area :address %>
  </div>
  <br>

  <div>
  <%= form.submit %>
  </div>
<% end %>

<p><%= link_to "Back",students_path %> || <%= link_to "Show",student_path %></p>

app/views/students/index.html.erb
<%= notice %>
<h1>All Student's</h1>
<p><%= link_to "New-Student",new_student_path %></p>
<table style="width:50%">
<thead>
  <tr>
    <td>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Email</th>
      <th>Age</th>
      <th>Adress</th> 
      <th colspan=3>Action</th>   
    </td>
  </tr>
</thead>
<tbody>
    <% @students.each do |student| %>
      <tr>
        <td>
            <th><%=student.first_name %></th>
            <th><%=student.last_name %></th>
            <th><%=student.email %></th>
            <th><%=student.age%></th>
            <th><%=student.address %></th>
            <th><%= link_to 'Show',student %></th>
            <th><%= link_to 'Edit',edit_student_path(student) %></th>
            <th><%= link_to "Delete",student, data: {turbo_method: :delete,turbo_confirm: "Are you sure?"} %></th> 
        </td>
      </tr>
    <%end%>
</tbody>
</table>

app/views/students/new.html.erb
<h1>New Student's</h1>
<%= form_with model: @student do |form| %>
  <% if @student.errors.any? %>
      <% @student.errors.full_messages.each do |messages| %>
          <p><%= messages %></p>
      <%end%>
  <%end%>

  <div>
  <%= form.label :first_name %><br>
  <%= form.text_field :first_name %>
  </div>
  <br>

  <div>
  <%= form.label :last_name %><br>
  <%= form.text_field :last_name %>
  </div>
  <br>

  </div>
  <%= form.label :email %><br>
  <%= form.text_field :email %>
  </div>
  <br><br>
  
  <div>
  <%= form.label :age %><br>
  <%= form.text_area :age %>
  </div>
  <br>

  <div>
  <%= form.label :address %><br>
  <%= form.text_area :address %>
  </div>
  <br>

  <div>
  <%= form.submit %>
  </div>
<% end %>

app/views/students/show.html.erb
<h1>Show Student's</h1>
<p><strong>First Name :-- </strong><%= @student.first_name %></p>
<p><strong>Last Name :-- </strong><%= @student.last_name %></p>
<p><strong>Email :-- </strong><%= @student.email %></p>
<p><strong>Age :-- </strong><%= @student.age %></p>
<p><strong>Address :-- </strong><%= @student.address %></p>

<%= link_to "Back",students_path %>||<%= link_to "Edit",edit_student_path %>

app/views/welcome/index.html.erb
<h1>Welcome Page</h1>